---
- name: Check if k3s agent is already installed
  stat:
    path: /usr/local/bin/k3s
  register: k3s_binary

- name: Install k3s agent and join cluster
  shell: |
    curl -sfL https://get.k3s.io | sh -s - agent \
      --server https://{{ controlplane_ip }}:6443 \
      --token {{ hostvars[groups['controlplane'][0]]['k3s_token'] }} \
  environment:
    INSTALL_K3S_VERSION: "{{ k3s_version }}"
  when: not k3s_binary.stat.exists

- name: Enable and start k3s-agent
  systemd:
    name: k3s-agent
    enabled: true
    state: started
